services:
  postgres:
    image: postgres:15
    container_name: platform-postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: platform-redis
    ports:
      - "6379:6379"

  user-service:
    build:
      context: ../services/user-service
    container_name: user-service
    environment:
      DATABASE_URL: postgres://appuser:apppassword@postgres:5432/appdb?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  gateway:
    build:
      context: ../apps/gateway
    container_name: gateway
    environment:
      USER_SERVICE_URL: http://user-service:8080
    depends_on:
      - user-service
    ports:
      - "3000:3000"

volumes:
  postgres_data: